"""Export quantized tensors into ROM-ready blobs.

Phase 1 exports a single real matvec (w1 of layer 0: 172 outputs x 64 inputs) so
the assembly kernel can be checked bit-exact and timed against a known MAC count.
The layout below is the one the full model will use.

Product table bias
------------------
The ROM's per-input table holds `x[j] * cb[u]`, which is signed, and adding a
signed 16-bit value into an int24 accumulator costs a sign-extension the SM83 has
no spare register for. Biasing every entry by BIAS makes the table unsigned, so
the third accumulator byte is a plain `adc a, 0`. The sum picks up `n * BIAS`,
a constant removed once per matvec rather than once per MAC.
"""

import struct
from pathlib import Path

import numpy as np

import quant as Q
import reference as ref

ROOT = Path(__file__).resolve().parent.parent
BUILD = ROOT / "build"
INC = ROOT / "src" / "model.inc"

BIAS = 1 << 14          # 16384 > 127*127, so every table entry is unsigned
WEIGHT_BITS = 4
CLASSIFIER_BITS = 8

# The product table is pinned at $FF80 so exported weight bytes can be complete
# HRAM offsets: `index * 2 + HLUT_BASE`. The kernel then loads a product with
# `ld c, a` / `ldh a, [c]` and no address arithmetic at all in the inner loop.
HLUT_BASE = 0x80


def product_table(x, codebook):
    """The 16 entries the ROM builds per input, as unsigned 16-bit."""
    return (x.astype(np.int32) * codebook.astype(np.int32) + BIAS).astype(np.uint16)


def matvec_expected(idx, codebook, x):
    """Exactly what the ROM will hold in its accumulators, bias included."""
    m, n = idx.shape
    acc = np.zeros(m, dtype=np.int64)
    for j in range(n):
        table = product_table(x[j], codebook).astype(np.int64)
        acc += table[idx[:, j]]
    return acc


def main():
    BUILD.mkdir(exist_ok=True)
    model = ref.Model()
    print("calibrating...", flush=True)
    sites = Q.calibrate(model)
    q = Q.quantize_model(model, sites, weight_bits=WEIGHT_BITS,
                         bits_override={"tok_emb": CLASSIFIER_BITS})

    # --- the Phase 1 test case: w1, layer 0 ---
    idx = q.indices["w1"][0]                 # (hidden_dim, dim) codebook indices
    cb = q.codebooks["w1"]
    m, n = idx.shape

    rng = np.random.default_rng(1234)
    x = rng.integers(-127, 128, size=n).astype(np.int8)

    # Weights input-major: for input j, m contiguous bytes, one per output.
    # Each byte is a ready-to-use HRAM offset into the product table.
    offsets = idx.T.astype(np.int32) * 2 + HLUT_BASE
    assert offsets.max() < HLUT_BASE + (1 << WEIGHT_BITS) * 2 <= 0x100
    packed = offsets.astype(np.uint8).tobytes()
    assert len(packed) == n * m

    expected = matvec_expected(idx, cb, x)
    assert expected.min() >= 0 and expected.max() < (1 << 24), "outside int24"

    (BUILD / "mv_weights.bin").write_bytes(packed)
    (BUILD / "mv_x.bin").write_bytes(x.astype(np.int8).tobytes())
    (BUILD / "mv_cb.bin").write_bytes(cb.astype(np.int8).tobytes())
    (BUILD / "mv_expected.bin").write_bytes(
        b"".join(struct.pack("<I", int(v))[:3] for v in expected)
    )

    INC.write_text(
        "; Generated by py/export.py - do not edit.\n"
        f"DEF MV_N EQU {n}          ; inputs\n"
        f"DEF MV_M EQU {m}          ; outputs\n"
        f"DEF MV_MACS EQU {n * m}\n"
        f"DEF MV_BIAS EQU {BIAS}\n"
        f"DEF CB_LEVELS EQU {1 << WEIGHT_BITS}\n"
        f"DEF HLUT_BASE EQU ${HLUT_BASE:02X}\n",
        encoding="utf-8",
    )
    print(f"w1[0]: {m} outputs x {n} inputs = {n * m:,} MACs")
    print(f"codebook: {list(cb)}")
    print(f"accumulator range: {expected.min():,} .. {expected.max():,}")


if __name__ == "__main__":
    main()
