"""Convert dhepper/font8x8 (public domain) into src/font.inc.

Emits 1bpp glyph data for ASCII 32..127 in order, so that VRAM tile index N
holds ASCII N+32. The ROM expands each byte to 2bpp at load time.

font8x8 stores each row LSB-first (bit 0 = leftmost pixel); the Game Boy wants
bit 7 = leftmost, so every row is bit-reversed here.
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "tools" / "font8x8_basic.h"
DST = ROOT / "src" / "font.inc"

FIRST, LAST = 32, 127


def parse(text):
    """Return a list of 128 glyphs, each a list of 8 row bytes."""
    glyphs = []
    for line in text.splitlines():
        # The declaration line opens a brace but never closes it, so requiring a
        # complete brace group is enough to skip it.
        m = re.search(r"\{([^{}]*)\}", line)
        if not m:
            continue
        row = [int(v, 16) for v in re.findall(r"0x([0-9a-fA-F]{2})", m.group(1))]
        if len(row) == 8:
            glyphs.append(row)
    return glyphs


def reverse_bits(b):
    return int(f"{b:08b}"[::-1], 2)


def main():
    if not SRC.exists():
        sys.exit(f"missing {SRC} - run .\\bootstrap.ps1 first")

    glyphs = parse(SRC.read_text(encoding="utf-8", errors="replace"))
    if len(glyphs) < LAST + 1:
        sys.exit(f"parsed only {len(glyphs)} glyphs from {SRC.name}, expected >= {LAST + 1}")

    out = [
        "; Generated by py/gen_font.py - do not edit.",
        "; Source: dhepper/font8x8 (Daniel Hepper, public domain).",
        f"; ASCII {FIRST}..{LAST}, 1bpp, 8 bytes per glyph. Tile index = ASCII - {FIRST}.",
        "",
        "FontData::",
    ]
    for code in range(FIRST, LAST + 1):
        rows = ",".join(f"${reverse_bits(b):02X}" for b in glyphs[code])
        label = chr(code) if code != 32 else "space"
        out.append(f"    db {rows}  ; {code} {label}")
    # Box-drawing pieces the ASCII font has no glyphs for. They sit directly
    # after the ASCII range, so Console_PutChar reaches them with codes 128+
    # and needs no special case: tile index is still ASCII - 32.
    #   line at row 3 / column 3, so corners meet cleanly
    H, V = 0xFF, 0x10
    border = {
        "TL": [0, 0, 0, 0x1F, V, V, V, V],
        "H":  [0, 0, 0, H, 0, 0, 0, 0],
        "TR": [0, 0, 0, 0xF0, V, V, V, V],
        "V":  [V, V, V, V, V, V, V, V],
        "BL": [V, V, V, 0x1F, 0, 0, 0, 0],
        "BR": [V, V, V, 0xF0, 0, 0, 0, 0],
        "LT": [V, V, V, 0x1F, V, V, V, V],
        "RT": [V, V, V, 0xF0, V, V, V, V],
    }
    for name, rows in border.items():
        out.append("    db " + ",".join(f"${r:02X}" for r in rows) + f"  ; {name}")

    out.append("")
    out.append(f"DEF FONT_GLYPHS EQU {LAST - FIRST + 1 + len(border)}")
    out.append("")

    DST.write_text("\n".join(out), encoding="utf-8")
    print(f"wrote {DST} ({LAST - FIRST + 1} glyphs)")


if __name__ == "__main__":
    main()
