; Generated by py/export5.py - do not edit.
INCLUDE "model.inc"

SECTION "tbl_rsqrt", ROM0
tbl_rsqrt:: INCBIN "build/blobs/tbl_rsqrt.bin"   ; 512 bytes

SECTION "tbl_qsq", ROM0
tbl_qsq:: INCBIN "build/blobs/tbl_qsq.bin"   ; 514 bytes

SECTION "sig_l0", ROM0
sig_l0:: INCBIN "build/blobs/sig_l0.bin"   ; 256 bytes

SECTION "sig_l1", ROM0
sig_l1:: INCBIN "build/blobs/sig_l1.bin"   ; 256 bytes

SECTION "sig_l2", ROM0
sig_l2:: INCBIN "build/blobs/sig_l2.bin"   ; 256 bytes

SECTION "relu2_tbl", ROM0, ALIGN[8]
relu2_tbl:: INCBIN "build/blobs/relu2_tbl.bin"   ; 768 bytes

SECTION "emb_rows_p0", ROMX
emb_rows_p0:: INCBIN "build/blobs/emb_rows_p0.bin"   ; 16384 bytes

SECTION "emb_rows_p1", ROMX
emb_rows_p1:: INCBIN "build/blobs/emb_rows_p1.bin"   ; 16384 bytes

SECTION "emb_rows_p2", ROMX
emb_rows_p2:: INCBIN "build/blobs/emb_rows_p2.bin"   ; 16384 bytes

SECTION "emb_rows_p3", ROMX
emb_rows_p3:: INCBIN "build/blobs/emb_rows_p3.bin"   ; 16384 bytes

SECTION "cls_w_p0", ROMX
cls_w_p0:: INCBIN "build/blobs/cls_w_p0.bin"   ; 6656 bytes

SECTION "cls_w_p1", ROMX
cls_w_p1:: INCBIN "build/blobs/cls_w_p1.bin"   ; 6656 bytes

SECTION "lut_cls_hi", ROMX
lut_cls_hi:: INCBIN "build/blobs/lut_cls_hi.bin"   ; 1 bytes

SECTION "lut_cls_lo", ROMX
lut_cls_lo:: INCBIN "build/blobs/lut_cls_lo.bin"   ; 1 bytes

SECTION "rms_att", ROM0
rms_att:: INCBIN "build/blobs/rms_att.bin"   ; 192 bytes

SECTION "rms_ffn", ROM0
rms_ffn:: INCBIN "build/blobs/rms_ffn.bin"   ; 192 bytes

SECTION "rms_final", ROM0
rms_final:: INCBIN "build/blobs/rms_final.bin"   ; 64 bytes

SECTION "rmsatt_shift", ROM0
rmsatt_shift:: INCBIN "build/blobs/rmsatt_shift.bin"   ; 3 bytes

SECTION "rmsffn_shift", ROM0
rmsffn_shift:: INCBIN "build/blobs/rmsffn_shift.bin"   ; 3 bytes

SECTION "wz_l0", ROMX
wz_l0:: INCBIN "build/blobs/wz_l0.bin"   ; 1408 bytes
wz_sh_l0:: INCBIN "build/blobs/wz_sh_l0.bin"   ; 64 bytes, in the bank of wz_l0

SECTION "wz_l1", ROMX
wz_l1:: INCBIN "build/blobs/wz_l1.bin"   ; 1408 bytes
wz_sh_l1:: INCBIN "build/blobs/wz_sh_l1.bin"   ; 64 bytes, in the bank of wz_l1

SECTION "wz_l2", ROMX
wz_l2:: INCBIN "build/blobs/wz_l2.bin"   ; 1408 bytes
wz_sh_l2:: INCBIN "build/blobs/wz_sh_l2.bin"   ; 64 bytes, in the bank of wz_l2

SECTION "wh_l0", ROMX
wh_l0:: INCBIN "build/blobs/wh_l0.bin"   ; 1408 bytes
wh_sh_l0:: INCBIN "build/blobs/wh_sh_l0.bin"   ; 64 bytes, in the bank of wh_l0

SECTION "wh_l1", ROMX
wh_l1:: INCBIN "build/blobs/wh_l1.bin"   ; 1408 bytes
wh_sh_l1:: INCBIN "build/blobs/wh_sh_l1.bin"   ; 64 bytes, in the bank of wh_l1

SECTION "wh_l2", ROMX
wh_l2:: INCBIN "build/blobs/wh_l2.bin"   ; 1408 bytes
wh_sh_l2:: INCBIN "build/blobs/wh_sh_l2.bin"   ; 64 bytes, in the bank of wh_l2

SECTION "wo_l0", ROMX
wo_l0:: INCBIN "build/blobs/wo_l0.bin"   ; 1408 bytes
wo_sh_l0:: INCBIN "build/blobs/wo_sh_l0.bin"   ; 64 bytes, in the bank of wo_l0

SECTION "wo_l1", ROMX
wo_l1:: INCBIN "build/blobs/wo_l1.bin"   ; 1408 bytes
wo_sh_l1:: INCBIN "build/blobs/wo_sh_l1.bin"   ; 64 bytes, in the bank of wo_l1

SECTION "wo_l2", ROMX
wo_l2:: INCBIN "build/blobs/wo_l2.bin"   ; 1408 bytes
wo_sh_l2:: INCBIN "build/blobs/wo_sh_l2.bin"   ; 64 bytes, in the bank of wo_l2

SECTION "router_l0", ROMX
router_l0:: INCBIN "build/blobs/router_l0.bin"   ; 88 bytes

SECTION "w1_l0_e0", ROMX
w1_l0_e0:: INCBIN "build/blobs/w1_l0_e0.bin"   ; 3872 bytes
w1_sh_l0_e0:: INCBIN "build/blobs/w1_sh_l0_e0.bin"   ; 176 bytes, in the bank of w1_l0_e0

SECTION "w2_l0_e0", ROMX
w2_l0_e0:: INCBIN "build/blobs/w2_l0_e0.bin"   ; 3776 bytes
w2_sh_l0_e0:: INCBIN "build/blobs/w2_sh_l0_e0.bin"   ; 64 bytes, in the bank of w2_l0_e0

SECTION "w2s_l0_e0", ROMX
w2s_l0_e0:: INCBIN "build/blobs/w2s_l0_e0.bin"   ; 8115 bytes

SECTION "w1_l0_e1", ROMX
w1_l0_e1:: INCBIN "build/blobs/w1_l0_e1.bin"   ; 3872 bytes
w1_sh_l0_e1:: INCBIN "build/blobs/w1_sh_l0_e1.bin"   ; 176 bytes, in the bank of w1_l0_e1

SECTION "w2_l0_e1", ROMX
w2_l0_e1:: INCBIN "build/blobs/w2_l0_e1.bin"   ; 3776 bytes
w2_sh_l0_e1:: INCBIN "build/blobs/w2_sh_l0_e1.bin"   ; 64 bytes, in the bank of w2_l0_e1

SECTION "w2s_l0_e1", ROMX
w2s_l0_e1:: INCBIN "build/blobs/w2s_l0_e1.bin"   ; 8044 bytes

SECTION "w1_l0_e2", ROMX
w1_l0_e2:: INCBIN "build/blobs/w1_l0_e2.bin"   ; 3872 bytes
w1_sh_l0_e2:: INCBIN "build/blobs/w1_sh_l0_e2.bin"   ; 176 bytes, in the bank of w1_l0_e2

SECTION "w2_l0_e2", ROMX
w2_l0_e2:: INCBIN "build/blobs/w2_l0_e2.bin"   ; 3776 bytes
w2_sh_l0_e2:: INCBIN "build/blobs/w2_sh_l0_e2.bin"   ; 64 bytes, in the bank of w2_l0_e2

SECTION "w2s_l0_e2", ROMX
w2s_l0_e2:: INCBIN "build/blobs/w2s_l0_e2.bin"   ; 8023 bytes

SECTION "w1_l0_e3", ROMX
w1_l0_e3:: INCBIN "build/blobs/w1_l0_e3.bin"   ; 3872 bytes
w1_sh_l0_e3:: INCBIN "build/blobs/w1_sh_l0_e3.bin"   ; 176 bytes, in the bank of w1_l0_e3

SECTION "w2_l0_e3", ROMX
w2_l0_e3:: INCBIN "build/blobs/w2_l0_e3.bin"   ; 3776 bytes
w2_sh_l0_e3:: INCBIN "build/blobs/w2_sh_l0_e3.bin"   ; 64 bytes, in the bank of w2_l0_e3

SECTION "w2s_l0_e3", ROMX
w2s_l0_e3:: INCBIN "build/blobs/w2s_l0_e3.bin"   ; 8133 bytes

SECTION "router_l1", ROMX
router_l1:: INCBIN "build/blobs/router_l1.bin"   ; 88 bytes

SECTION "w1_l1_e0", ROMX
w1_l1_e0:: INCBIN "build/blobs/w1_l1_e0.bin"   ; 3872 bytes
w1_sh_l1_e0:: INCBIN "build/blobs/w1_sh_l1_e0.bin"   ; 176 bytes, in the bank of w1_l1_e0

SECTION "w2_l1_e0", ROMX
w2_l1_e0:: INCBIN "build/blobs/w2_l1_e0.bin"   ; 3776 bytes
w2_sh_l1_e0:: INCBIN "build/blobs/w2_sh_l1_e0.bin"   ; 64 bytes, in the bank of w2_l1_e0

SECTION "w2s_l1_e0", ROMX
w2s_l1_e0:: INCBIN "build/blobs/w2s_l1_e0.bin"   ; 7932 bytes

SECTION "w1_l1_e1", ROMX
w1_l1_e1:: INCBIN "build/blobs/w1_l1_e1.bin"   ; 3872 bytes
w1_sh_l1_e1:: INCBIN "build/blobs/w1_sh_l1_e1.bin"   ; 176 bytes, in the bank of w1_l1_e1

SECTION "w2_l1_e1", ROMX
w2_l1_e1:: INCBIN "build/blobs/w2_l1_e1.bin"   ; 3776 bytes
w2_sh_l1_e1:: INCBIN "build/blobs/w2_sh_l1_e1.bin"   ; 64 bytes, in the bank of w2_l1_e1

SECTION "w2s_l1_e1", ROMX
w2s_l1_e1:: INCBIN "build/blobs/w2s_l1_e1.bin"   ; 7941 bytes

SECTION "w1_l1_e2", ROMX
w1_l1_e2:: INCBIN "build/blobs/w1_l1_e2.bin"   ; 3872 bytes
w1_sh_l1_e2:: INCBIN "build/blobs/w1_sh_l1_e2.bin"   ; 176 bytes, in the bank of w1_l1_e2

SECTION "w2_l1_e2", ROMX
w2_l1_e2:: INCBIN "build/blobs/w2_l1_e2.bin"   ; 3776 bytes
w2_sh_l1_e2:: INCBIN "build/blobs/w2_sh_l1_e2.bin"   ; 64 bytes, in the bank of w2_l1_e2

SECTION "w2s_l1_e2", ROMX
w2s_l1_e2:: INCBIN "build/blobs/w2s_l1_e2.bin"   ; 7886 bytes

SECTION "w1_l1_e3", ROMX
w1_l1_e3:: INCBIN "build/blobs/w1_l1_e3.bin"   ; 3872 bytes
w1_sh_l1_e3:: INCBIN "build/blobs/w1_sh_l1_e3.bin"   ; 176 bytes, in the bank of w1_l1_e3

SECTION "w2_l1_e3", ROMX
w2_l1_e3:: INCBIN "build/blobs/w2_l1_e3.bin"   ; 3776 bytes
w2_sh_l1_e3:: INCBIN "build/blobs/w2_sh_l1_e3.bin"   ; 64 bytes, in the bank of w2_l1_e3

SECTION "w2s_l1_e3", ROMX
w2s_l1_e3:: INCBIN "build/blobs/w2s_l1_e3.bin"   ; 7997 bytes

SECTION "router_l2", ROMX
router_l2:: INCBIN "build/blobs/router_l2.bin"   ; 88 bytes

SECTION "w1_l2_e0", ROMX
w1_l2_e0:: INCBIN "build/blobs/w1_l2_e0.bin"   ; 3872 bytes
w1_sh_l2_e0:: INCBIN "build/blobs/w1_sh_l2_e0.bin"   ; 176 bytes, in the bank of w1_l2_e0

SECTION "w2_l2_e0", ROMX
w2_l2_e0:: INCBIN "build/blobs/w2_l2_e0.bin"   ; 3776 bytes
w2_sh_l2_e0:: INCBIN "build/blobs/w2_sh_l2_e0.bin"   ; 64 bytes, in the bank of w2_l2_e0

SECTION "w2s_l2_e0", ROMX
w2s_l2_e0:: INCBIN "build/blobs/w2s_l2_e0.bin"   ; 7670 bytes

SECTION "w1_l2_e1", ROMX
w1_l2_e1:: INCBIN "build/blobs/w1_l2_e1.bin"   ; 3872 bytes
w1_sh_l2_e1:: INCBIN "build/blobs/w1_sh_l2_e1.bin"   ; 176 bytes, in the bank of w1_l2_e1

SECTION "w2_l2_e1", ROMX
w2_l2_e1:: INCBIN "build/blobs/w2_l2_e1.bin"   ; 3776 bytes
w2_sh_l2_e1:: INCBIN "build/blobs/w2_sh_l2_e1.bin"   ; 64 bytes, in the bank of w2_l2_e1

SECTION "w2s_l2_e1", ROMX
w2s_l2_e1:: INCBIN "build/blobs/w2s_l2_e1.bin"   ; 7767 bytes

SECTION "w1_l2_e2", ROMX
w1_l2_e2:: INCBIN "build/blobs/w1_l2_e2.bin"   ; 3872 bytes
w1_sh_l2_e2:: INCBIN "build/blobs/w1_sh_l2_e2.bin"   ; 176 bytes, in the bank of w1_l2_e2

SECTION "w2_l2_e2", ROMX
w2_l2_e2:: INCBIN "build/blobs/w2_l2_e2.bin"   ; 3776 bytes
w2_sh_l2_e2:: INCBIN "build/blobs/w2_sh_l2_e2.bin"   ; 64 bytes, in the bank of w2_l2_e2

SECTION "w2s_l2_e2", ROMX
w2s_l2_e2:: INCBIN "build/blobs/w2s_l2_e2.bin"   ; 7888 bytes

SECTION "w1_l2_e3", ROMX
w1_l2_e3:: INCBIN "build/blobs/w1_l2_e3.bin"   ; 3872 bytes
w1_sh_l2_e3:: INCBIN "build/blobs/w1_sh_l2_e3.bin"   ; 176 bytes, in the bank of w1_l2_e3

SECTION "w2_l2_e3", ROMX
w2_l2_e3:: INCBIN "build/blobs/w2_l2_e3.bin"   ; 3776 bytes
w2_sh_l2_e3:: INCBIN "build/blobs/w2_sh_l2_e3.bin"   ; 64 bytes, in the bank of w2_l2_e3

SECTION "w2s_l2_e3", ROMX
w2s_l2_e3:: INCBIN "build/blobs/w2s_l2_e3.bin"   ; 7502 bytes

SECTION "vocab_data", ROMX
vocab_data:: INCBIN "build/blobs/vocab_data.bin"   ; 7051 bytes

SECTION "enc_all", ROMX
enc_all:: INCBIN "build/blobs/enc_all.bin"   ; 9101 bytes

SECTION "prompt", ROM0
prompt:: INCBIN "build/blobs/prompt.bin"   ; 12 bytes

SECTION "test_x", ROM0
test_x:: INCBIN "build/blobs/test_x.bin"   ; 64 bytes

SECTION "test_h1", ROM0
test_h1:: INCBIN "build/blobs/test_h1.bin"   ; 176 bytes

SECTION "test_gate_zl", ROM0
test_gate_zl:: INCBIN "build/blobs/test_gate_zl.bin"   ; 64 bytes

SECTION "test_gate_h", ROM0
test_gate_h:: INCBIN "build/blobs/test_gate_h.bin"   ; 64 bytes

SECTION "test_gate_ht", ROM0
test_gate_ht:: INCBIN "build/blobs/test_gate_ht.bin"   ; 64 bytes

SECTION "test_gate_out", ROM0
test_gate_out:: INCBIN "build/blobs/test_gate_out.bin"   ; 64 bytes

SECTION "test_sp_a", ROMX
test_sp_a:: INCBIN "build/blobs/test_sp_a.bin"   ; 176 bytes

SECTION "test_sp_b", ROMX
test_sp_b:: INCBIN "build/blobs/test_sp_b.bin"   ; 176 bytes

SECTION "Model manifest", ROM0
emb_banks:: db BANK(emb_rows_p0), BANK(emb_rows_p1), BANK(emb_rows_p2), BANK(emb_rows_p3)
emb_addrs:: dw emb_rows_p0, emb_rows_p1, emb_rows_p2, emb_rows_p3
cls_banks:: db BANK(cls_w_p0), BANK(cls_w_p1)
cls_addrs:: dw cls_w_p0, cls_w_p1
wz_banks:: db BANK(wz_l0), BANK(wz_l1), BANK(wz_l2)
wz_addrs:: dw wz_l0, wz_l1, wz_l2
wz_shifts:: dw wz_sh_l0, wz_sh_l1, wz_sh_l2
wz_shbanks:: db BANK(wz_sh_l0), BANK(wz_sh_l1), BANK(wz_sh_l2)
wh_banks:: db BANK(wh_l0), BANK(wh_l1), BANK(wh_l2)
wh_addrs:: dw wh_l0, wh_l1, wh_l2
wh_shifts:: dw wh_sh_l0, wh_sh_l1, wh_sh_l2
wh_shbanks:: db BANK(wh_sh_l0), BANK(wh_sh_l1), BANK(wh_sh_l2)
wo_banks:: db BANK(wo_l0), BANK(wo_l1), BANK(wo_l2)
wo_addrs:: dw wo_l0, wo_l1, wo_l2
wo_shifts:: dw wo_sh_l0, wo_sh_l1, wo_sh_l2
wo_shbanks:: db BANK(wo_sh_l0), BANK(wo_sh_l1), BANK(wo_sh_l2)
router_banks:: db BANK(router_l0), BANK(router_l1), BANK(router_l2)
router_addrs:: dw router_l0, router_l1, router_l2
w1_banks:: db BANK(w1_l0_e0), BANK(w1_l0_e1), BANK(w1_l0_e2), BANK(w1_l0_e3), BANK(w1_l1_e0), BANK(w1_l1_e1), BANK(w1_l1_e2), BANK(w1_l1_e3), BANK(w1_l2_e0), BANK(w1_l2_e1), BANK(w1_l2_e2), BANK(w1_l2_e3)
w1_addrs:: dw w1_l0_e0, w1_l0_e1, w1_l0_e2, w1_l0_e3, w1_l1_e0, w1_l1_e1, w1_l1_e2, w1_l1_e3, w1_l2_e0, w1_l2_e1, w1_l2_e2, w1_l2_e3
w1_shifts:: dw w1_sh_l0_e0, w1_sh_l0_e1, w1_sh_l0_e2, w1_sh_l0_e3, w1_sh_l1_e0, w1_sh_l1_e1, w1_sh_l1_e2, w1_sh_l1_e3, w1_sh_l2_e0, w1_sh_l2_e1, w1_sh_l2_e2, w1_sh_l2_e3
w1_shbanks:: db BANK(w1_sh_l0_e0), BANK(w1_sh_l0_e1), BANK(w1_sh_l0_e2), BANK(w1_sh_l0_e3), BANK(w1_sh_l1_e0), BANK(w1_sh_l1_e1), BANK(w1_sh_l1_e2), BANK(w1_sh_l1_e3), BANK(w1_sh_l2_e0), BANK(w1_sh_l2_e1), BANK(w1_sh_l2_e2), BANK(w1_sh_l2_e3)
w2_banks:: db BANK(w2_l0_e0), BANK(w2_l0_e1), BANK(w2_l0_e2), BANK(w2_l0_e3), BANK(w2_l1_e0), BANK(w2_l1_e1), BANK(w2_l1_e2), BANK(w2_l1_e3), BANK(w2_l2_e0), BANK(w2_l2_e1), BANK(w2_l2_e2), BANK(w2_l2_e3)
w2_addrs:: dw w2_l0_e0, w2_l0_e1, w2_l0_e2, w2_l0_e3, w2_l1_e0, w2_l1_e1, w2_l1_e2, w2_l1_e3, w2_l2_e0, w2_l2_e1, w2_l2_e2, w2_l2_e3
w2_shifts:: dw w2_sh_l0_e0, w2_sh_l0_e1, w2_sh_l0_e2, w2_sh_l0_e3, w2_sh_l1_e0, w2_sh_l1_e1, w2_sh_l1_e2, w2_sh_l1_e3, w2_sh_l2_e0, w2_sh_l2_e1, w2_sh_l2_e2, w2_sh_l2_e3
w2_shbanks:: db BANK(w2_sh_l0_e0), BANK(w2_sh_l0_e1), BANK(w2_sh_l0_e2), BANK(w2_sh_l0_e3), BANK(w2_sh_l1_e0), BANK(w2_sh_l1_e1), BANK(w2_sh_l1_e2), BANK(w2_sh_l1_e3), BANK(w2_sh_l2_e0), BANK(w2_sh_l2_e1), BANK(w2_sh_l2_e2), BANK(w2_sh_l2_e3)
w2s_banks:: db BANK(w2s_l0_e0), BANK(w2s_l0_e1), BANK(w2s_l0_e2), BANK(w2s_l0_e3), BANK(w2s_l1_e0), BANK(w2s_l1_e1), BANK(w2s_l1_e2), BANK(w2s_l1_e3), BANK(w2s_l2_e0), BANK(w2s_l2_e1), BANK(w2s_l2_e2), BANK(w2s_l2_e3)
w2s_addrs:: dw w2s_l0_e0, w2s_l0_e1, w2s_l0_e2, w2s_l0_e3, w2s_l1_e0, w2s_l1_e1, w2s_l1_e2, w2s_l1_e3, w2s_l2_e0, w2s_l2_e1, w2s_l2_e2, w2s_l2_e3
sig_tables:: dw sig_l0, sig_l1, sig_l2
