; Generated by py/export5.py - do not edit.
INCLUDE "model.inc"

SECTION "tbl_rsqrt", ROM0
tbl_rsqrt:: INCBIN "build/blobs/tbl_rsqrt.bin"   ; 512 bytes

SECTION "tbl_qsq", ROM0
tbl_qsq:: INCBIN "build/blobs/tbl_qsq.bin"   ; 514 bytes

SECTION "sig_l0", ROM0
sig_l0:: INCBIN "build/blobs/sig_l0.bin"   ; 256 bytes

SECTION "sig_l1", ROM0
sig_l1:: INCBIN "build/blobs/sig_l1.bin"   ; 256 bytes

SECTION "sig_l2", ROM0
sig_l2:: INCBIN "build/blobs/sig_l2.bin"   ; 256 bytes

SECTION "r2_shift", ROM0
r2_shift:: INCBIN "build/blobs/r2_shift.bin"   ; 3 bytes

SECTION "emb_rows_p0", ROMX
emb_rows_p0:: INCBIN "build/blobs/emb_rows_p0.bin"   ; 16384 bytes

SECTION "emb_rows_p1", ROMX
emb_rows_p1:: INCBIN "build/blobs/emb_rows_p1.bin"   ; 16384 bytes

SECTION "cls_w_p0", ROMX
cls_w_p0:: INCBIN "build/blobs/cls_w_p0.bin"   ; 11264 bytes

SECTION "lut_cls_hi", ROMX
lut_cls_hi:: INCBIN "build/blobs/lut_cls_hi.bin"   ; 1 bytes

SECTION "lut_cls_lo", ROMX
lut_cls_lo:: INCBIN "build/blobs/lut_cls_lo.bin"   ; 1 bytes

SECTION "rms_att", ROM0
rms_att:: INCBIN "build/blobs/rms_att.bin"   ; 192 bytes

SECTION "rms_ffn", ROM0
rms_ffn:: INCBIN "build/blobs/rms_ffn.bin"   ; 192 bytes

SECTION "rms_final", ROM0
rms_final:: INCBIN "build/blobs/rms_final.bin"   ; 64 bytes

SECTION "rmsatt_shift", ROM0
rmsatt_shift:: INCBIN "build/blobs/rmsatt_shift.bin"   ; 3 bytes

SECTION "rmsffn_shift", ROM0
rmsffn_shift:: INCBIN "build/blobs/rmsffn_shift.bin"   ; 3 bytes

SECTION "wz_l0", ROMX
wz_l0:: INCBIN "build/blobs/wz_l0.bin"   ; 1408 bytes

SECTION "wz_sh_l0", ROM0
wz_sh_l0:: INCBIN "build/blobs/wz_sh_l0.bin"   ; 64 bytes

SECTION "wz_l1", ROMX
wz_l1:: INCBIN "build/blobs/wz_l1.bin"   ; 1408 bytes

SECTION "wz_sh_l1", ROM0
wz_sh_l1:: INCBIN "build/blobs/wz_sh_l1.bin"   ; 64 bytes

SECTION "wz_l2", ROMX
wz_l2:: INCBIN "build/blobs/wz_l2.bin"   ; 1408 bytes

SECTION "wz_sh_l2", ROM0
wz_sh_l2:: INCBIN "build/blobs/wz_sh_l2.bin"   ; 64 bytes

SECTION "wh_l0", ROMX
wh_l0:: INCBIN "build/blobs/wh_l0.bin"   ; 1408 bytes

SECTION "wh_sh_l0", ROM0
wh_sh_l0:: INCBIN "build/blobs/wh_sh_l0.bin"   ; 64 bytes

SECTION "wh_l1", ROMX
wh_l1:: INCBIN "build/blobs/wh_l1.bin"   ; 1408 bytes

SECTION "wh_sh_l1", ROM0
wh_sh_l1:: INCBIN "build/blobs/wh_sh_l1.bin"   ; 64 bytes

SECTION "wh_l2", ROMX
wh_l2:: INCBIN "build/blobs/wh_l2.bin"   ; 1408 bytes

SECTION "wh_sh_l2", ROM0
wh_sh_l2:: INCBIN "build/blobs/wh_sh_l2.bin"   ; 64 bytes

SECTION "wo_l0", ROMX
wo_l0:: INCBIN "build/blobs/wo_l0.bin"   ; 1408 bytes

SECTION "wo_sh_l0", ROM0
wo_sh_l0:: INCBIN "build/blobs/wo_sh_l0.bin"   ; 64 bytes

SECTION "wo_l1", ROMX
wo_l1:: INCBIN "build/blobs/wo_l1.bin"   ; 1408 bytes

SECTION "wo_sh_l1", ROM0
wo_sh_l1:: INCBIN "build/blobs/wo_sh_l1.bin"   ; 64 bytes

SECTION "wo_l2", ROMX
wo_l2:: INCBIN "build/blobs/wo_l2.bin"   ; 1408 bytes

SECTION "wo_sh_l2", ROM0
wo_sh_l2:: INCBIN "build/blobs/wo_sh_l2.bin"   ; 64 bytes

SECTION "router_l0", ROMX
router_l0:: INCBIN "build/blobs/router_l0.bin"   ; 88 bytes

SECTION "w1_l0_e0", ROMX
w1_l0_e0:: INCBIN "build/blobs/w1_l0_e0.bin"   ; 3872 bytes

SECTION "w2_l0_e0", ROMX
w2_l0_e0:: INCBIN "build/blobs/w2_l0_e0.bin"   ; 3776 bytes

SECTION "w1_sh_l0_e0", ROM0
w1_sh_l0_e0:: INCBIN "build/blobs/w1_sh_l0_e0.bin"   ; 176 bytes

SECTION "w2_sh_l0_e0", ROM0
w2_sh_l0_e0:: INCBIN "build/blobs/w2_sh_l0_e0.bin"   ; 64 bytes

SECTION "w1_l0_e1", ROMX
w1_l0_e1:: INCBIN "build/blobs/w1_l0_e1.bin"   ; 3872 bytes

SECTION "w2_l0_e1", ROMX
w2_l0_e1:: INCBIN "build/blobs/w2_l0_e1.bin"   ; 3776 bytes

SECTION "w1_sh_l0_e1", ROM0
w1_sh_l0_e1:: INCBIN "build/blobs/w1_sh_l0_e1.bin"   ; 176 bytes

SECTION "w2_sh_l0_e1", ROM0
w2_sh_l0_e1:: INCBIN "build/blobs/w2_sh_l0_e1.bin"   ; 64 bytes

SECTION "w1_l0_e2", ROMX
w1_l0_e2:: INCBIN "build/blobs/w1_l0_e2.bin"   ; 3872 bytes

SECTION "w2_l0_e2", ROMX
w2_l0_e2:: INCBIN "build/blobs/w2_l0_e2.bin"   ; 3776 bytes

SECTION "w1_sh_l0_e2", ROM0
w1_sh_l0_e2:: INCBIN "build/blobs/w1_sh_l0_e2.bin"   ; 176 bytes

SECTION "w2_sh_l0_e2", ROM0
w2_sh_l0_e2:: INCBIN "build/blobs/w2_sh_l0_e2.bin"   ; 64 bytes

SECTION "w1_l0_e3", ROMX
w1_l0_e3:: INCBIN "build/blobs/w1_l0_e3.bin"   ; 3872 bytes

SECTION "w2_l0_e3", ROMX
w2_l0_e3:: INCBIN "build/blobs/w2_l0_e3.bin"   ; 3776 bytes

SECTION "w1_sh_l0_e3", ROM0
w1_sh_l0_e3:: INCBIN "build/blobs/w1_sh_l0_e3.bin"   ; 176 bytes

SECTION "w2_sh_l0_e3", ROM0
w2_sh_l0_e3:: INCBIN "build/blobs/w2_sh_l0_e3.bin"   ; 64 bytes

SECTION "router_l1", ROMX
router_l1:: INCBIN "build/blobs/router_l1.bin"   ; 88 bytes

SECTION "w1_l1_e0", ROMX
w1_l1_e0:: INCBIN "build/blobs/w1_l1_e0.bin"   ; 3872 bytes

SECTION "w2_l1_e0", ROMX
w2_l1_e0:: INCBIN "build/blobs/w2_l1_e0.bin"   ; 3776 bytes

SECTION "w1_sh_l1_e0", ROM0
w1_sh_l1_e0:: INCBIN "build/blobs/w1_sh_l1_e0.bin"   ; 176 bytes

SECTION "w2_sh_l1_e0", ROM0
w2_sh_l1_e0:: INCBIN "build/blobs/w2_sh_l1_e0.bin"   ; 64 bytes

SECTION "w1_l1_e1", ROMX
w1_l1_e1:: INCBIN "build/blobs/w1_l1_e1.bin"   ; 3872 bytes

SECTION "w2_l1_e1", ROMX
w2_l1_e1:: INCBIN "build/blobs/w2_l1_e1.bin"   ; 3776 bytes

SECTION "w1_sh_l1_e1", ROM0
w1_sh_l1_e1:: INCBIN "build/blobs/w1_sh_l1_e1.bin"   ; 176 bytes

SECTION "w2_sh_l1_e1", ROM0
w2_sh_l1_e1:: INCBIN "build/blobs/w2_sh_l1_e1.bin"   ; 64 bytes

SECTION "w1_l1_e2", ROMX
w1_l1_e2:: INCBIN "build/blobs/w1_l1_e2.bin"   ; 3872 bytes

SECTION "w2_l1_e2", ROMX
w2_l1_e2:: INCBIN "build/blobs/w2_l1_e2.bin"   ; 3776 bytes

SECTION "w1_sh_l1_e2", ROM0
w1_sh_l1_e2:: INCBIN "build/blobs/w1_sh_l1_e2.bin"   ; 176 bytes

SECTION "w2_sh_l1_e2", ROM0
w2_sh_l1_e2:: INCBIN "build/blobs/w2_sh_l1_e2.bin"   ; 64 bytes

SECTION "w1_l1_e3", ROMX
w1_l1_e3:: INCBIN "build/blobs/w1_l1_e3.bin"   ; 3872 bytes

SECTION "w2_l1_e3", ROMX
w2_l1_e3:: INCBIN "build/blobs/w2_l1_e3.bin"   ; 3776 bytes

SECTION "w1_sh_l1_e3", ROM0
w1_sh_l1_e3:: INCBIN "build/blobs/w1_sh_l1_e3.bin"   ; 176 bytes

SECTION "w2_sh_l1_e3", ROM0
w2_sh_l1_e3:: INCBIN "build/blobs/w2_sh_l1_e3.bin"   ; 64 bytes

SECTION "router_l2", ROMX
router_l2:: INCBIN "build/blobs/router_l2.bin"   ; 88 bytes

SECTION "w1_l2_e0", ROMX
w1_l2_e0:: INCBIN "build/blobs/w1_l2_e0.bin"   ; 3872 bytes

SECTION "w2_l2_e0", ROMX
w2_l2_e0:: INCBIN "build/blobs/w2_l2_e0.bin"   ; 3776 bytes

SECTION "w1_sh_l2_e0", ROM0
w1_sh_l2_e0:: INCBIN "build/blobs/w1_sh_l2_e0.bin"   ; 176 bytes

SECTION "w2_sh_l2_e0", ROM0
w2_sh_l2_e0:: INCBIN "build/blobs/w2_sh_l2_e0.bin"   ; 64 bytes

SECTION "w1_l2_e1", ROMX
w1_l2_e1:: INCBIN "build/blobs/w1_l2_e1.bin"   ; 3872 bytes

SECTION "w2_l2_e1", ROMX
w2_l2_e1:: INCBIN "build/blobs/w2_l2_e1.bin"   ; 3776 bytes

SECTION "w1_sh_l2_e1", ROM0
w1_sh_l2_e1:: INCBIN "build/blobs/w1_sh_l2_e1.bin"   ; 176 bytes

SECTION "w2_sh_l2_e1", ROM0
w2_sh_l2_e1:: INCBIN "build/blobs/w2_sh_l2_e1.bin"   ; 64 bytes

SECTION "w1_l2_e2", ROMX
w1_l2_e2:: INCBIN "build/blobs/w1_l2_e2.bin"   ; 3872 bytes

SECTION "w2_l2_e2", ROMX
w2_l2_e2:: INCBIN "build/blobs/w2_l2_e2.bin"   ; 3776 bytes

SECTION "w1_sh_l2_e2", ROM0
w1_sh_l2_e2:: INCBIN "build/blobs/w1_sh_l2_e2.bin"   ; 176 bytes

SECTION "w2_sh_l2_e2", ROM0
w2_sh_l2_e2:: INCBIN "build/blobs/w2_sh_l2_e2.bin"   ; 64 bytes

SECTION "w1_l2_e3", ROMX
w1_l2_e3:: INCBIN "build/blobs/w1_l2_e3.bin"   ; 3872 bytes

SECTION "w2_l2_e3", ROMX
w2_l2_e3:: INCBIN "build/blobs/w2_l2_e3.bin"   ; 3776 bytes

SECTION "w1_sh_l2_e3", ROM0
w1_sh_l2_e3:: INCBIN "build/blobs/w1_sh_l2_e3.bin"   ; 176 bytes

SECTION "w2_sh_l2_e3", ROM0
w2_sh_l2_e3:: INCBIN "build/blobs/w2_sh_l2_e3.bin"   ; 64 bytes

SECTION "vocab_data", ROMX
vocab_data:: INCBIN "build/blobs/vocab_data.bin"   ; 2162 bytes

SECTION "vocab_off", ROM0
vocab_off:: INCBIN "build/blobs/vocab_off.bin"   ; 1024 bytes

SECTION "enc_all", ROMX
enc_all:: INCBIN "build/blobs/enc_all.bin"   ; 4212 bytes

SECTION "prompt", ROM0
prompt:: INCBIN "build/blobs/prompt.bin"   ; 14 bytes

SECTION "test_x", ROM0
test_x:: INCBIN "build/blobs/test_x.bin"   ; 64 bytes

SECTION "test_h1", ROM0
test_h1:: INCBIN "build/blobs/test_h1.bin"   ; 176 bytes

SECTION "test_gate_zl", ROM0
test_gate_zl:: INCBIN "build/blobs/test_gate_zl.bin"   ; 64 bytes

SECTION "test_gate_h", ROM0
test_gate_h:: INCBIN "build/blobs/test_gate_h.bin"   ; 64 bytes

SECTION "test_gate_ht", ROM0
test_gate_ht:: INCBIN "build/blobs/test_gate_ht.bin"   ; 64 bytes

SECTION "test_gate_out", ROM0
test_gate_out:: INCBIN "build/blobs/test_gate_out.bin"   ; 64 bytes

SECTION "Model manifest", ROM0
emb_banks:: db BANK(emb_rows_p0), BANK(emb_rows_p1)
emb_addrs:: dw emb_rows_p0, emb_rows_p1
cls_banks:: db BANK(cls_w_p0)
cls_addrs:: dw cls_w_p0
wz_banks:: db BANK(wz_l0), BANK(wz_l1), BANK(wz_l2)
wz_addrs:: dw wz_l0, wz_l1, wz_l2
wz_shifts:: dw wz_sh_l0, wz_sh_l1, wz_sh_l2
wz_shbanks:: db BANK(wz_sh_l0), BANK(wz_sh_l1), BANK(wz_sh_l2)
wh_banks:: db BANK(wh_l0), BANK(wh_l1), BANK(wh_l2)
wh_addrs:: dw wh_l0, wh_l1, wh_l2
wh_shifts:: dw wh_sh_l0, wh_sh_l1, wh_sh_l2
wh_shbanks:: db BANK(wh_sh_l0), BANK(wh_sh_l1), BANK(wh_sh_l2)
wo_banks:: db BANK(wo_l0), BANK(wo_l1), BANK(wo_l2)
wo_addrs:: dw wo_l0, wo_l1, wo_l2
wo_shifts:: dw wo_sh_l0, wo_sh_l1, wo_sh_l2
wo_shbanks:: db BANK(wo_sh_l0), BANK(wo_sh_l1), BANK(wo_sh_l2)
router_banks:: db BANK(router_l0), BANK(router_l1), BANK(router_l2)
router_addrs:: dw router_l0, router_l1, router_l2
w1_banks:: db BANK(w1_l0_e0), BANK(w1_l0_e1), BANK(w1_l0_e2), BANK(w1_l0_e3), BANK(w1_l1_e0), BANK(w1_l1_e1), BANK(w1_l1_e2), BANK(w1_l1_e3), BANK(w1_l2_e0), BANK(w1_l2_e1), BANK(w1_l2_e2), BANK(w1_l2_e3)
w1_addrs:: dw w1_l0_e0, w1_l0_e1, w1_l0_e2, w1_l0_e3, w1_l1_e0, w1_l1_e1, w1_l1_e2, w1_l1_e3, w1_l2_e0, w1_l2_e1, w1_l2_e2, w1_l2_e3
w1_shifts:: dw w1_sh_l0_e0, w1_sh_l0_e1, w1_sh_l0_e2, w1_sh_l0_e3, w1_sh_l1_e0, w1_sh_l1_e1, w1_sh_l1_e2, w1_sh_l1_e3, w1_sh_l2_e0, w1_sh_l2_e1, w1_sh_l2_e2, w1_sh_l2_e3
w1_shbanks:: db BANK(w1_sh_l0_e0), BANK(w1_sh_l0_e1), BANK(w1_sh_l0_e2), BANK(w1_sh_l0_e3), BANK(w1_sh_l1_e0), BANK(w1_sh_l1_e1), BANK(w1_sh_l1_e2), BANK(w1_sh_l1_e3), BANK(w1_sh_l2_e0), BANK(w1_sh_l2_e1), BANK(w1_sh_l2_e2), BANK(w1_sh_l2_e3)
w2_banks:: db BANK(w2_l0_e0), BANK(w2_l0_e1), BANK(w2_l0_e2), BANK(w2_l0_e3), BANK(w2_l1_e0), BANK(w2_l1_e1), BANK(w2_l1_e2), BANK(w2_l1_e3), BANK(w2_l2_e0), BANK(w2_l2_e1), BANK(w2_l2_e2), BANK(w2_l2_e3)
w2_addrs:: dw w2_l0_e0, w2_l0_e1, w2_l0_e2, w2_l0_e3, w2_l1_e0, w2_l1_e1, w2_l1_e2, w2_l1_e3, w2_l2_e0, w2_l2_e1, w2_l2_e2, w2_l2_e3
w2_shifts:: dw w2_sh_l0_e0, w2_sh_l0_e1, w2_sh_l0_e2, w2_sh_l0_e3, w2_sh_l1_e0, w2_sh_l1_e1, w2_sh_l1_e2, w2_sh_l1_e3, w2_sh_l2_e0, w2_sh_l2_e1, w2_sh_l2_e2, w2_sh_l2_e3
w2_shbanks:: db BANK(w2_sh_l0_e0), BANK(w2_sh_l0_e1), BANK(w2_sh_l0_e2), BANK(w2_sh_l0_e3), BANK(w2_sh_l1_e0), BANK(w2_sh_l1_e1), BANK(w2_sh_l1_e2), BANK(w2_sh_l1_e3), BANK(w2_sh_l2_e0), BANK(w2_sh_l2_e1), BANK(w2_sh_l2_e2), BANK(w2_sh_l2_e3)
sig_tables:: dw sig_l0, sig_l1, sig_l2
